logo: '<img src=/Momentum/assets/img/himalayan.jpg>' # add logo name
logo-img: momentum_logo_clear_older.png
logo-img2: momentum_logo_clear.png
title: Momentum - Make Your Move
description: > # this means to ignore newlines until "baseurl:"
  An alternative social contract for men prioritizing transparency over self-promotion.
permalink: ':title/'
baseurl: "" # the sub-path of your site, e.g. /blog
url: "https://www.gomomentum.org" # Was http://kimardenmiller.github.io" base hostname & protocol for your site

# Banner settings
poster: momentum_gm.jpg # add banner video. Add your video file to the folder video
video_mp4: momentum_gm.mp4 # add banner video. Add your video file to the folder video
video_ogv: momentum_gm.ogv # add banner video. Add your video file to the folder video
video_webm: momentum_gm.webm # add banner video. Add your video file to the folder video
video_playback_rate: .7

# banner title
banner-title: Momentum
# banner description
banner-desc: A community of men who support each other to be our best.
#banner-desc: An alternative social contract between men that places transparency over self-promotion.
# banner call to action
banner-call-to-action: Learn More

# Author settings
author-name: Momentum
author-pic: momentum_logo_darker.png  # gif portable logo
about-author: Momentum is a local, not-for-profit men’s community.
#about-image: bramhall_circle.jpg

# contact settings
email: info@gomomentum.org # contact email  TODO 8:gomomentum.org URL: test live and alert Moe it's coming
website: http://gomomentum.org/ # our main website
contact: /contact/
phone:  # phone number unused as of May 16, 2018

# Social link -- Aug 16, 2018social links working on final site, but only FB has a good preview
meet_up_url:    https://www.meetup.com/GoMomentum/events/
facebook_url:   https://www.facebook.com/GoMomentum/
discourse_url:  http://discourse.gomomentum.org/
google_url:    # add url link
pinterest_url: # add url link
dribbble_url:  # add url link

# Disqus
discus_identifier: gomomentum # add your discus identifier

# Newsletter
mailchimp: gomomentum.us18.list-manage.com/subscribe/post?u=cd428163397aafa9f23b0ee8a&amp;id=f700eb71e1

# Tracker TODO 8: take a look at traffic
analytics: UA-19737734-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", ".idea/workspace.xml"]

sass:
    sass_dir: assets/css/sass

collections:
  momentum_content:
    output: true